services:
  courier-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgis
      - migrosRedis

  migrosRedis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: migrosRedis
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_DB: migros_db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    container_name: postgis