spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/migros_db
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG

application:
  default-strategy: haversine